import { vi } from "vitest";
import type { CraftelApi } from "../api/craftel";
import type { Document, DocumentRevision, PhaseSession, Project, Run, RunEvent, RunState, Stage, Task } from "../api/types";
export const now = "2026-07-21T12:00:00Z";
export const project = (extra: Partial<Project> = {}): Project => ({ id: "p1", name: "Alpha", work_dir: "/tmp/alpha", available: true, created_at: now, last_opened_at: now, ...extra });
export const task = (stage: Stage = "inbox", extra: Partial<Task> = {}): Task => ({ id: "T0001", project_id: "p1", title: "Useful title", content: "Representative content for this card", stage, relative_dir: ".craftel/tasks/T0001", review_approved: false, created_at: now, updated_at: now, ...extra });
export const document = (path="tasks/T0001/SPEC.md", extra:Partial<Document>={}):Document=>({project_id:"p1",relative_path:path,task_id:"T0001",title:path.split("/").at(-1)!,body:"# Draft",content_hash:"hash-1",present:true,indexed_at:now,...extra});
export const revision = (extra:Partial<DocumentRevision>={}):DocumentRevision=>({id:"rev-1",project_id:"p1",relative_path:"tasks/T0001/SPEC.md",content_hash:"old-hash",content:[35,32,79,108,100],captured_at:now,cause:"edit",sequence:1,...extra});
export const session = (extra:Partial<PhaseSession>={}):PhaseSession=>({id:"s1",project_id:"p1",task_id:"T0001",phase:"defining",harness:"cursor",external_session_id:"external-1",created_at:now,updated_at:now,...extra});
export const run = (state:RunState="succeeded",extra:Partial<Run>={}):Run=>({id:"r1",session_id:"s1",project_id:"p1",task_id:"T0001",sequence:1,state,prompt:"go",harness:"cursor",harness_version:"1.0",model:"model",work_dir:"/tmp/alpha",request_id:null,started_at:now,finished_at:state==="running"?null:now,exit_code:0,stderr:"",final_result:null,stop_requested_at:null,error:null,stage_at_start:"defining",workflow_event_id_before:null,prompt_kind:"defining",prompt_version:1,observed_transition_event_id:null,missing_transition:false,created_at:now,updated_at:now,...extra});
export const runEvent = (sequence:number,extra:Partial<RunEvent>={}):RunEvent=>({run_id:"r1",sequence,kind:"assistant",event_at:now,display_text:`event ${sequence}`,tool_name:null,tool_call_id:null,raw_json:"{}",...extra});
export function deferred<T>() { let resolve!:(value:T)=>void,reject!:(reason?:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no});return {promise,resolve,reject}; }
export function fakeApi(overrides: Partial<CraftelApi> = {}): CraftelApi {
  return { listProjects: vi.fn().mockResolvedValue([]), selectProjectDirectory: vi.fn().mockResolvedValue(null), registerProject: vi.fn(), openProject: vi.fn(), removeProject: vi.fn(), listTasks: vi.fn().mockResolvedValue([]), createTask: vi.fn(), updateTask: vi.fn(), moveTask: vi.fn(), nextTask:vi.fn(), listDocuments:vi.fn().mockResolvedValue([]),documentStatus:vi.fn(),readDocument:vi.fn(),searchDocuments:vi.fn(),writeDocument:vi.fn(),listDocumentRevisions:vi.fn(),restoreDocumentRevision:vi.fn(),startCurrentPhase:vi.fn(),stopRun:vi.fn(),getSession:vi.fn(),listSessions:vi.fn().mockResolvedValue([]),listRuns:vi.fn().mockResolvedValue([]),listActiveRuns:vi.fn().mockResolvedValue([]),getRun:vi.fn(),listRunEvents:vi.fn().mockResolvedValue([]),followUp:vi.fn(),subscribe:vi.fn().mockResolvedValue(()=>{}), ...overrides };
}
