import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { vi } from "vitest";
import { ProjectSwitcher } from "./ProjectSwitcher";
import { deferred, fakeApi, project } from "../test/fake";

test("loads and switches registered projects through openProject", async () => { const a = project(), b = project({ id: "p2", name: "Beta" }); const api = fakeApi({ listProjects: vi.fn().mockResolvedValue([a, b]), openProject: vi.fn().mockResolvedValue(b) }); const select = vi.fn(); render(<ProjectSwitcher api={api} selected={a} onSelect={select} />); await userEvent.click(await screen.findByRole("button", { name: "Beta" })); expect(api.openProject).toHaveBeenCalledWith("p2"); expect(select).toHaveBeenCalledWith(b); });
test("registers, opens, refreshes, and selects the folder chosen in the Craftel dialog", async () => { const p = project(); const select = vi.fn(); const api = fakeApi({ listDirectory: vi.fn().mockResolvedValue({path:"/tmp",parent:"/",entries:[{name:"alpha",path:"/tmp/alpha",hidden:false}]}), registerProject: vi.fn().mockResolvedValue(p), openProject: vi.fn().mockResolvedValue(p) }); render(<ProjectSwitcher api={api} selected={null} onSelect={select} />); await userEvent.click(screen.getByRole("button", { name: "Open Project" })); await userEvent.click(await screen.findByRole("button", { name: "alpha" })); await userEvent.click(screen.getByRole("button", { name: "Add Project" })); await waitFor(() => expect(api.registerProject).toHaveBeenCalledWith("alpha", "/tmp/alpha")); expect(api.openProject).toHaveBeenCalledWith(p.id); expect(select).toHaveBeenCalledWith(p); expect(screen.queryByRole("dialog")).not.toBeInTheDocument(); });
test("shows and removes a missing registration without a file operation", async () => { const p = project({ available: false }); const api = fakeApi({ listProjects: vi.fn().mockResolvedValueOnce([p]).mockResolvedValue([]), removeProject: vi.fn().mockResolvedValue(undefined) }); render(<ProjectSwitcher api={api} selected={p} onSelect={vi.fn()} />); expect(await screen.findByText("Directory missing")).toBeInTheDocument(); await userEvent.click(screen.getByRole("button", { name: /Remove Registration/ })); expect(api.removeProject).toHaveBeenCalledWith("p1"); });
test("a stale project load cannot select after the switcher is gone",async()=>{const late=deferred<ReturnType<typeof project>[]>(),select=vi.fn();const view=render(<ProjectSwitcher api={fakeApi({listProjects:vi.fn(()=>late.promise)})} selected={null} onSelect={select}/>);view.unmount();late.resolve([project({id:"stale"})]);await Promise.resolve();expect(select).not.toHaveBeenCalled();});
test("a stale initial load cannot replace the newly opened project", async () => { const initial=deferred<ReturnType<typeof project>[]>(),opened=project({id:"new",name:"New"}),select=vi.fn();const api=fakeApi({listProjects:vi.fn().mockReturnValueOnce(initial.promise).mockResolvedValueOnce([opened]),listDirectory:vi.fn().mockResolvedValue({path:"/tmp/new",parent:"/tmp",entries:[]}),registerProject:vi.fn().mockResolvedValue(opened),openProject:vi.fn().mockResolvedValue(opened)});render(<ProjectSwitcher api={api} selected={null} onSelect={select}/>);await userEvent.click(screen.getByRole("button",{name:"Open Project"}));await userEvent.click(await screen.findByRole("button",{name:"Add Project"}));await waitFor(()=>expect(select).toHaveBeenCalledWith(opened));initial.resolve([project({id:"old",name:"Old"})]);await Promise.resolve();expect(select).toHaveBeenCalledTimes(1); });
test("checks the unsaved-work guard before registration", async () => { const register=vi.fn();render(<ProjectSwitcher api={fakeApi({listDirectory:vi.fn().mockResolvedValue({path:"/tmp/new",parent:"/tmp",entries:[]}),registerProject:register})} selected={project()} canSelect={()=>false} onSelect={vi.fn()}/>);await userEvent.click(screen.getByRole("button",{name:"Open Project"}));const add=await screen.findByRole("button",{name:"Add Project"});await userEvent.click(add);expect(register).not.toHaveBeenCalled();expect(add).toBeEnabled(); });
