import { useCallback, useEffect, useRef, useState } from "react";
import type { CraftelApi } from "../api/craftel";
import { errorMessage } from "../api/craftel";
import type { Phase, PhaseSession, Run, RunEvent } from "../api/types";

const active=(run:Run)=>run.state==="queued"||run.state==="running";
export function duration(run:Run, now=Date.now()){const start=run.started_at?Date.parse(run.started_at):Date.parse(run.created_at);const end=active(run)?now:run.finished_at?Date.parse(run.finished_at):Date.parse(run.updated_at);return Math.max(0,Math.floor((end-start)/1000));}
export function mergeEvents(previous:RunEvent[],incoming:RunEvent[]){const map=new Map(previous.map(e=>[`${e.run_id}:${e.sequence}`,e]));incoming.forEach(e=>map.set(`${e.run_id}:${e.sequence}`,e));return [...map.values()].sort((a,b)=>a.sequence-b.sequence);}

export function RunActivity({api,projectId,taskId,phase}:{api:CraftelApi;projectId:string;taskId:string;phase?:Phase}){
 const [sessions,setSessions]=useState<PhaseSession[]>([]),[runs,setRuns]=useState<Run[]>([]),[selected,setSelected]=useState<Run|null>(null),[events,setEvents]=useState<RunEvent[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[,tick]=useState(0);
 const generation=useRef(0),refreshGeneration=useRef(0), selectedRef=useRef<Run|null>(null), highWater=useRef(new Map<string,number>()), fetching=useRef<number|null>(null), queued=useRef(new Set<number>());
 selectedRef.current=selected;
 const refresh=useCallback(async(gen=generation.current)=>{const request=++refreshGeneration.current;try{const ss=(await api.listSessions(projectId,taskId)).sort((a,b)=>b.updated_at.localeCompare(a.updated_at)||b.created_at.localeCompare(a.created_at));const rr=(await Promise.all(ss.map(s=>api.listRuns(s.id)))).flat().sort((a,b)=>a.created_at.localeCompare(b.created_at));if(gen!==generation.current||request!==refreshGeneration.current)return;const eligibleSessions=ss.filter(s=>!phase||s.phase===phase),currentSessionIds=new Set((phase?eligibleSessions.slice(0,1):eligibleSessions).map(s=>s.id)),currentRuns=rr.filter(r=>currentSessionIds.has(r.session_id));setSessions(ss);setRuns(rr);setSelected(v=>currentRuns.find(r=>r.id===v?.id)??currentRuns.at(-1)??(phase?null:rr.at(-1)??null));setError("");}catch(e){if(gen===generation.current&&request===refreshGeneration.current)setError(errorMessage(e));}finally{if(gen===generation.current&&request===refreshGeneration.current)setLoading(false)}},[api,projectId,taskId,phase]);
 const fetchEvents=useCallback(async()=>{const gen=generation.current;queued.current.add(gen);if(fetching.current===gen)return;fetching.current=gen;try{while(queued.current.delete(gen)){const run=selectedRef.current;if(!run)continue;let after=highWater.current.get(run.id)??0;for(;;){const page=await api.listRunEvents(run.id,after,100);if(gen!==generation.current||run.id!==selectedRef.current?.id)return;if(!page.length)break;setEvents(old=>mergeEvents(old,page));const max=Math.max(after,...page.map(e=>e.sequence));highWater.current.set(run.id,max);after=max;if(page.length<100)break;}}if(gen===generation.current)setError("");}catch(e){if(gen===generation.current)setError(errorMessage(e));}finally{if(fetching.current===gen){fetching.current=null;if(gen===generation.current&&queued.current.has(gen))void fetchEvents()}queued.current.delete(gen)}},[api]);
 useEffect(()=>{const gen=++generation.current;let dead=false;const offs:(()=>void)[]=[];setLoading(true);setSessions([]);setRuns([]);setEvents([]);highWater.current.clear();void(async()=>{await refresh(gen);if(dead)return;for(const name of ["run_event","run_changed"] as const){try{const off=await api.subscribe(name,()=>{if(dead)return;void refresh(gen);void fetchEvents();});if(dead)off();else offs.push(off);}catch(e){if(!dead&&gen===generation.current)setError(errorMessage(e));}}// Close the query-to-subscribe window; notifications are hints, not data.
 await refresh(gen);await fetchEvents();})();return()=>{dead=true;++generation.current;++refreshGeneration.current;offs.forEach(off=>off());};},[api,projectId,taskId,refresh,fetchEvents]);
 useEffect(()=>{if(selected){highWater.current.set(selected.id,0);setEvents([]);void fetchEvents();}},[selected?.id,fetchEvents]);
 useEffect(()=>{if(!selected||!active(selected))return;const id=setInterval(()=>tick(v=>v+1),1000);return()=>clearInterval(id);},[selected?.id,selected?.state]);
 const phaseSessions=sessions.filter(s=>!phase||s.phase===phase),currentSessions=phaseSessions.slice(0,1),historicalSessions=[...phaseSessions.slice(1),...sessions.filter(s=>phase&&s.phase!==phase)];
 const sessionView=(s:PhaseSession)=><section className="session-history" key={s.id}><h3>{s.phase} session</h3>{runs.filter(r=>r.session_id===s.id).map(r=><button className="run-link" aria-current={selected?.id===r.id?"true":undefined} key={r.id} onClick={()=>setSelected(r)}>Run {r.sequence} · {r.state}</button>)}</section>;
 return <div className="activity"><h2>Session activity</h2>{loading&&<p role="status">Loading activity…</p>}{error&&<p role="alert">{error} <button onClick={()=>void refresh()}>Retry</button></p>}{!loading&&!currentSessions.length&&!error?<div className="activity-empty"><strong>No phase session yet</strong><p>Start the current phase to create a durable conversation and run history.</p></div>:currentSessions.map(sessionView)}{historicalSessions.length>0&&<details className="phase-history"><summary>Earlier phase history · {historicalSessions.length}</summary>{historicalSessions.map(sessionView)}</details>}
 {selected&&<section className="run-view"><div className="run-view-title"><h3>Run {selected.sequence}</h3><span className={`run-state run-${selected.state}`}>{selected.state}</span></div>{selected.missing_transition&&<p className="notice">The agent exited without a workflow transition.</p>}{selected.state==="interrupted"&&<p className="notice">The process was interrupted and was not resumed automatically.</p>}<EventList events={events}/>{selected.final_result&&<p className="run-result"><strong>Result</strong>{selected.final_result}</p>}{selected.stderr&&<pre className="diagnostic">{selected.stderr.slice(0,4000)}</pre>}{selected.error&&<p role="alert">{selected.error.slice(0,500)}</p>}<details className="run-metadata"><summary>Run details</summary><dl><dt>Duration</dt><dd>{duration(selected)}s</dd><dt>Model</dt><dd>{selected.model??"Unknown"}</dd><dt>Harness</dt><dd>{selected.harness}{selected.harness_version?` ${selected.harness_version}`:""}</dd></dl></details></section>}</div>;
}
function EventList({events}:{events:RunEvent[]}){const completed=new Map(events.filter(e=>e.kind==="tool_complete"&&e.tool_call_id).map(e=>[e.tool_call_id,e]));return <div className="event-stream">{events.filter(e=>!(e.kind==="tool_complete"&&e.tool_call_id)).map(e=>{if(e.kind==="assistant")return <div className="assistant" key={e.sequence}><span>Agent</span><p>{e.display_text}</p></div>;if(e.kind==="user")return <div className="user-message" key={e.sequence}><span>You</span><p>{e.display_text}</p></div>;if(e.kind==="tool_start"){const done=e.tool_call_id?completed.get(e.tool_call_id):undefined;return <details key={e.sequence}><summary>{e.tool_name??"Tool"} · {done?"completed":"running"}</summary><pre className="diagnostic">{done?.display_text??e.display_text??done?.raw_json??e.raw_json}</pre></details>}return <details key={e.sequence}><summary>{e.kind==="unknown"?"Unknown event":e.kind}</summary><pre className="diagnostic">{e.display_text??e.raw_json}</pre></details>})}</div>}
