import { useEffect, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import rehypeSanitize from "rehype-sanitize";
import type { CraftelApi } from "../api/craftel";
import { errorCode, errorMessage } from "../api/craftel";
import type { Document, DocumentRevision, Phase, PhaseSession, Project, Run, Task } from "../api/types";
import { RunActivity } from "./RunActivity";
import { workspaceModel, type WorkspaceAction } from "./workspaceModel";

const stageLabels = { inbox: "Inbox", defining: "Defining", implementation: "Implementation", reviewing: "Reviewing", done: "Done" } as const;
const categoryOrder = ["Specification", "Decisions", "Discussions", "Plans", "Reviews", "Notes", "Subtasks", "Other"];
function documentCategory(path:string) {
  const lower=path.toLowerCase(),name=lower.split("/").at(-1);
  if(name==="spec.md")return "Specification";
  for(const [prefix,label] of [["decision","Decisions"],["discussion","Discussions"],["plan","Plans"],["review","Reviews"],["note","Notes"],["subtask","Subtasks"]] as const)if(name?.startsWith(prefix))return label;
  for(const [part,label] of [["/decisions/","Decisions"],["/discussions/","Discussions"],["/plans/","Plans"],["/reviews/","Reviews"],["/notes/","Notes"],["/subtasks/","Subtasks"]] as const)if(lower.includes(part))return label;
  return "Other";
}
function preferredDocument(documents:Document[],stage:Task["stage"]){
  const categories=stage==="defining"?["Specification"]:stage==="implementation"?["Plans","Specification"]:["Reviews","Specification"];
  for(const category of categories){const match=documents.filter(document=>document.present&&documentCategory(document.relative_path)===category).sort((a,b)=>b.indexed_at.localeCompare(a.indexed_at))[0];if(match)return match}
  return documents.find(document=>document.present)??documents[0];
}
function pathInsideTask(path:string,task:Task){const parts=path.split("/");const root=parts.findIndex(part=>part.split("-")[0]===task.id);return root>=0?parts.slice(root+1):[parts.at(-1)!]}
function taskProjection(task:Task){return `# ${task.title}\n\n## Task metadata\n\n- **ID:** ${task.id}\n- **Stage:** ${stageLabels[task.stage]}\n- **Created:** ${new Date(task.created_at).toLocaleString()}\n- **Updated:** ${new Date(task.updated_at).toLocaleString()}\n\n## Content\n\n${task.content}\n\n## Artifacts\n\n- Specification: [SPEC.md](./SPEC.md)\n\n> This view is generated from CRAFTEL's SQLite task metadata. Update task details or workflow state through CRAFTEL; agent-authored details belong in SPEC.md and the supporting document directories.`}

export function TaskWorkspace({api,project,task,onBack}:{api:CraftelApi;project:Project;task:Task;onBack():void}) {
  const [documents,setDocuments]=useState<Document[]>([]), [selected,setSelected]=useState<Document|null>(null);
  const [draft,setDraft]=useState(""), [editorMode,setEditorMode]=useState<"edit"|"preview"|"split">("edit"), [managedTask,setManagedTask]=useState(false), [loading,setLoading]=useState(true), [error,setError]=useState(""), [conflict,setConflict]=useState(false);
  const [currentTask,setCurrentTask]=useState(task),[active,setActive]=useState<Run|null>(null),[latest,setLatest]=useState<{session:PhaseSession;run:Run}|null>(null),[sessions,setSessions]=useState<PhaseSession[]>([]),[runs,setRuns]=useState<Run[]>([]),[controlsLoaded,setControlsLoaded]=useState(false),[pending,setPending]=useState(false),[followUp,setFollowUp]=useState(""),[controlError,setControlError]=useState("");
  const [revisions,setRevisions]=useState<DocumentRevision[]>([]),[revision,setRevision]=useState<DocumentRevision|null>(null),[showRevisions,setShowRevisions]=useState(false);
  const [panel,setPanel]=useState<"documents"|"activity">("documents");const treeGeneration=useRef(0),controlGeneration=useRef(0),selectionGeneration=useRef(0),editVersion=useRef(0),dirty=useRef(false),selectionExplicit=useRef(false),managedTaskRef=useRef(false),selectedRef=useRef<Document|null>(null),taskRef=useRef(currentTask),stageRef=useRef(currentTask.stage),actionLock=useRef(false),revisionButton=useRef<HTMLButtonElement>(null),dialog=useRef<HTMLElement>(null);selectedRef.current=selected;taskRef.current=currentTask;managedTaskRef.current=managedTask;
  const loadTree=async()=>{ const mine=++treeGeneration.current; setLoading(true); try { const docs=(await api.listDocuments(project.id,true)).filter(d=>d.task_id===task.id).sort((a,b)=>categoryOrder.indexOf(documentCategory(a.relative_path))-categoryOrder.indexOf(documentCategory(b.relative_path))||a.relative_path.localeCompare(b.relative_path)); if(mine!==treeGeneration.current)return; setDocuments(docs); setError("");const current=selectedRef.current,preferred=preferredDocument(docs,taskRef.current.stage);if(!current&&!managedTaskRef.current){if(preferred)await open(preferred);else setManagedTask(true)}else if(current&&!dirty.current){if(!selectionExplicit.current&&preferred&&preferred.relative_path!==current.relative_path)await open(preferred);else {const changed=docs.find(document=>document.relative_path===current.relative_path);if(changed&&(changed.content_hash!==current.content_hash||changed.present!==current.present))await open(changed)}} } catch(e){if(mine===treeGeneration.current)setError(errorMessage(e));} finally{if(mine===treeGeneration.current)setLoading(false);} };
  const open=async(doc:Document,explicit=false)=>{const mine=++selectionGeneration.current,startedAt=editVersion.current;try{const current=await api.readDocument(project.id,doc.relative_path);if(mine!==selectionGeneration.current||(!explicit&&(dirty.current||editVersion.current!==startedAt)))return;selectionExplicit.current=explicit;setManagedTask(false);setSelected(current);setDraft(current.body);dirty.current=false;setConflict(false);setError("");}catch(e){if(mine===selectionGeneration.current)setError(errorMessage(e));}};
  const openManagedTask=()=>{selectionGeneration.current++;selectionExplicit.current=true;setManagedTask(true);setSelected(null);dirty.current=false;setConflict(false);setError("")};
  useEffect(()=>{let dead=false,off:(()=>void)|undefined;void loadTree();void api.subscribe("document_changed",payload=>{const hint=payload as {project_id?:string};if(!dead&&hint.project_id===project.id)void loadTree()}).then(value=>{if(dead)value();else off=value});return()=>{dead=true;treeGeneration.current++;selectionGeneration.current++;off?.()};},[project.id,task.id]);
  const refreshControls=async()=>{const mine=++controlGeneration.current;try{const [tasks,loadedSessions]=await Promise.all([api.listTasks(project.id),api.listSessions(project.id,task.id)]);const loadedRuns=(await Promise.all(loadedSessions.map(s=>api.listRuns(s.id)))).flat();if(mine!==controlGeneration.current)return;const fresh=tasks.find(t=>t.id===task.id)??task;const phase=fresh.stage;const phaseSessions=loadedSessions.filter(s=>s.phase===phase).sort((a,b)=>b.updated_at.localeCompare(a.updated_at));const session=phaseSessions[0],run=session?loadedRuns.filter(r=>r.session_id===session.id).sort((a,b)=>b.sequence-a.sequence)[0]:undefined;setCurrentTask(fresh);setSessions(loadedSessions);setRuns(loadedRuns);setActive(loadedRuns.find(r=>r.state==="queued"||r.state==="running")??null);setLatest(session&&run?{session,run}:null);setControlError("");}catch(e){if(mine===controlGeneration.current)setControlError(`Could not load controls: ${errorMessage(e)}`)}finally{if(mine===controlGeneration.current)setControlsLoaded(true)}};
  useEffect(()=>{let dead=false,off:(()=>void)|undefined;void(async()=>{await refreshControls();if(dead)return;try{const unsubscribe=await api.subscribe("run_changed",()=>{if(!dead)void refreshControls()});if(dead)unsubscribe();else off=unsubscribe;await refreshControls()}catch(e){if(!dead)setControlError(`Could not watch controls: ${errorMessage(e)}`)}})();return()=>{dead=true;controlGeneration.current++;off?.()}},[project.id,task.id]);
  useEffect(()=>{if(stageRef.current===currentTask.stage)return;stageRef.current=currentTask.stage;selectionExplicit.current=false;void loadTree()},[currentTask.stage]);
  const save=async()=>{if(!selected)return;const startedAt=editVersion.current;try{const saved=await api.writeDocument(project.id,selected.relative_path,draft,{state:"present",hash:selected.content_hash});setSelected(saved);if(editVersion.current===startedAt){setDraft(saved.body);dirty.current=false}setConflict(false);setError("");}catch(e){setError(errorMessage(e));setConflict(errorCode(e)==="conflict");}};
  const reload=()=>selected&&void open(selected,true);
  const action=async(kind:WorkspaceAction)=>{if(actionLock.current)return;actionLock.current=true;setPending(true);try{if(kind==="advance")setCurrentTask(await api.nextTask(project.id,task.id));else if(kind==="start")await api.startCurrentPhase(project.id,task.id);else if(kind==="stop"&&active)await api.stopRun(active.id);else if(kind==="follow"&&latest&&followUp.trim()){await api.followUp(latest.session.id,followUp.trim());setFollowUp("")}await refreshControls();setControlError("");}catch(e){setControlError(`Could not ${kind}: ${errorMessage(e)}`)}finally{actionLock.current=false;setPending(false)}};
  const browse=async()=>{if(!selected)return;try{const values=await api.listDocumentRevisions(project.id,selected.relative_path);setRevisions(values.sort((a,b)=>b.captured_at.localeCompare(a.captured_at)));setRevision(values[0]??null);setShowRevisions(true);}catch(e){setError(errorMessage(e));}};
  const restore=async()=>{if(!selected||!revision||!window.confirm("Restore this revision? A new revision will be created."))return;try{const saved=await api.restoreDocumentRevision(project.id,selected.relative_path,revision.id,selected.present?{state:"present",hash:selected.content_hash}:{state:"missing"});setSelected(saved);setDraft(saved.body);await loadTree();await browse();setError("");}catch(e){setError(errorMessage(e));}};
  useEffect(()=>{if(!showRevisions)return;const backgrounds=[...document.querySelectorAll<HTMLElement>(".workspace > :not(.scrim)")];const previous=document.activeElement as HTMLElement|null;const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setShowRevisions(false);if(e.key==="Tab"&&dialog.current){const f=[...dialog.current.querySelectorAll<HTMLElement>('button:not([disabled]),[tabindex="0"]')];if(!f.length)return;const first=f[0],last=f.at(-1)!;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener("keydown",key);dialog.current?.querySelector<HTMLElement>("button")?.focus();backgrounds.forEach(node=>node.setAttribute("inert",""));return()=>{document.removeEventListener("keydown",key);backgrounds.forEach(node=>node.removeAttribute("inert"));(revisionButton.current??previous)?.focus()}},[showRevisions]);
  const terminal=latest&&!["queued","running"].includes(latest.run.state),canFollow=Boolean(terminal&&["defining","implementation"].includes(currentTask.stage)&&latest.session.external_session_id);
  const latestReviewSession=sessions.filter(s=>s.phase==="reviewing").sort((a,b)=>b.updated_at.localeCompare(a.updated_at))[0],latestImplementationSession=sessions.filter(s=>s.phase==="implementation").sort((a,b)=>b.updated_at.localeCompare(a.updated_at))[0],latestReviewRun=latestReviewSession&&runs.filter(run=>run.session_id===latestReviewSession.id).sort((a,b)=>b.sequence-a.sequence)[0];
  const reviewReturned=currentTask.stage==="implementation"&&Boolean(latestReviewRun?.observed_transition_event_id&&(!latestImplementationSession||latestReviewSession.updated_at>latestImplementationSession.updated_at));
  const model=workspaceModel(currentTask,{active:Boolean(active),reviewReturned,resumable:canFollow});
  const directoryName=currentTask.relative_dir.split("/").at(-1)??currentTask.id,rootDocuments:Document[]=[],documentFolders=new Map<string,Document[]>();for(const document of documents){const path=pathInsideTask(document.relative_path,currentTask);if(path.length===1)rootDocuments.push(document);else{const folder=path.slice(0,-1).join("/");(documentFolders.get(folder)??(documentFolders.set(folder,[]),documentFolders.get(folder)!)).push(document)}}
  const currentStageIndex=Object.keys(stageLabels).indexOf(currentTask.stage);
  const readOnly=currentTask.stage==="done";
  return <section className="workspace"><header className="workspace-head"><button onClick={onBack}>← Board</button><div className="workspace-title"><span className="task-id">{task.id}</span><h1>{task.title}</h1></div><span className="stage-badge">{stageLabels[currentTask.stage]}</span></header>
    <section className={`phase-context tone-${model.tone}`} aria-labelledby="phase-status"><ol className="phase-progress" aria-label="Task workflow">{Object.entries(stageLabels).map(([stage,label],index)=><li key={stage} aria-current={stage===currentTask.stage?"step":undefined} className={index<currentStageIndex?"complete":undefined}><span>{String(index+1).padStart(2,"0")}</span>{label}</li>)}</ol><div className="phase-copy"><p className="eyebrow">CURRENT PHASE · {stageLabels[currentTask.stage].toUpperCase()}</p><h2 id="phase-status">{model.status}</h2><p>{model.description}</p><small>Primary artifact · <strong>{model.artifact}</strong></small></div><div className="phase-action">{!controlsLoaded?<span role="status">Loading current state…</span>:model.primary&&model.primary.kind!=="follow"&&<button className="primary" disabled={pending} onClick={()=>void action(model.primary!.kind)}>{model.primary.label}</button>}</div></section>
    {controlError&&<div role="alert" className="notice">{controlError} <button onClick={()=>void refreshControls()}>Retry controls</button></div>}
    <div className="mobile-tabs" role="tablist" aria-label="Workspace panels"><button role="tab" aria-selected={panel==="documents"} onClick={()=>setPanel("documents")}>Documents</button><button role="tab" aria-selected={panel==="activity"} onClick={()=>setPanel("activity")}>Activity</button></div>
    {error&&<div className="notice" role="alert">{error} <button onClick={()=>void loadTree()}>Retry</button></div>}{conflict&&<div className="notice" role="alert">This document changed elsewhere. Your edits are preserved. <button onClick={reload}>Reload</button> <button onClick={()=>void navigator.clipboard?.writeText(draft)}>Copy edits</button></div>}
    <div className={`workspace-grid panel-${panel}`}><nav className="document-tree" aria-label="Task documents"><header className="tree-root"><strong>{directoryName}/</strong><small>Task workspace</small></header><button className="managed-file" aria-current={managedTask?"page":undefined} onClick={openManagedTask}><span>TASK.md</span><small>managed · read-only</small></button>{loading?<p role="status">Loading documents…</p>:<>{rootDocuments.map(d=><button key={d.relative_path} aria-current={selected?.relative_path===d.relative_path?"page":undefined} onClick={()=>void open(d,true)}><span>{pathInsideTask(d.relative_path,currentTask).at(-1)}{!d.present?" (deleted)":""}</span><small>{documentCategory(d.relative_path)}</small></button>)}{[...documentFolders.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([folder,folderDocuments])=><div className="tree-folder" key={folder}><div className="tree-group">{folder}/</div>{folderDocuments.sort((a,b)=>a.relative_path.localeCompare(b.relative_path)).map(d=><button key={d.relative_path} aria-current={selected?.relative_path===d.relative_path?"page":undefined} onClick={()=>void open(d,true)}>{pathInsideTask(d.relative_path,currentTask).at(-1)}{!d.present?" (deleted)":""}</button>)}</div>)}{documents.length===0&&<div className="tree-empty"><strong>No agent documents yet</strong><p>SPEC.md and phase artifacts will appear inside this directory.</p></div>}</>}</nav>
      <section className="editor">{managedTask?<><div className="editor-tools"><div><strong>TASK.md</strong><small>SQLite metadata projection · read-only</small></div></div><article className="markdown managed-task"><ReactMarkdown rehypePlugins={[rehypeSanitize]}>{taskProjection(currentTask)}</ReactMarkdown></article></>:selected?<><div className="editor-tools"><div><strong>{selected.relative_path.split("/").at(-1)}</strong><small>{documentCategory(selected.relative_path)}</small></div>{!readOnly&&<div className="editor-modes" role="group" aria-label="Editor mode"><button onClick={()=>setEditorMode("edit")} aria-pressed={editorMode==="edit"}>Edit</button><button onClick={()=>setEditorMode("preview")} aria-pressed={editorMode==="preview"}>Preview</button><button onClick={()=>setEditorMode("split")} aria-pressed={editorMode==="split"}>Split</button></div>}<button ref={revisionButton} onClick={()=>void browse()}>Revisions</button>{!readOnly&&<button disabled={!selected.present} onClick={()=>void save()}>Save</button>}</div>{readOnly||editorMode==="preview"?<article className="markdown"><ReactMarkdown rehypePlugins={[rehypeSanitize]}>{draft}</ReactMarkdown></article>:editorMode==="split"?<div className="split-editor"><textarea aria-label="Markdown document" value={draft} disabled={!selected.present} onChange={e=>{editVersion.current++;dirty.current=true;setDraft(e.target.value)}}/><article className="markdown" aria-label="Live Markdown preview"><ReactMarkdown rehypePlugins={[rehypeSanitize]}>{draft}</ReactMarkdown></article></div>:<textarea aria-label="Markdown document" value={draft} disabled={!selected.present} onChange={e=>{editVersion.current++;dirty.current=true;setDraft(e.target.value)}}/>}</>:<div className="editor-empty"><span aria-hidden="true">◇</span><h2>No agent document selected</h2><p>{active?"The agent is working. New or changed phase documents will appear here automatically.":"No indexed artifact exists for this phase yet. Use the stage action above when you are ready to continue."}</p></div>}</section>
      <aside className="phase-panel"><header><p className="eyebrow">CURRENT PHASE AGENT</p><h2>{stageLabels[currentTask.stage]}</h2><p>{model.artifact}</p></header>{model.composer&&<div className="phase-composer"><label>{model.composer.label}<textarea value={followUp} placeholder={model.composer.placeholder} onChange={e=>setFollowUp(e.target.value)}/></label><button className={model.primary?.kind==="follow"?"primary":undefined} disabled={pending||!followUp.trim()} onClick={()=>void action("follow")}>{model.composer.actionLabel}</button><small>Starts another run in the same phase session.</small></div>}<RunActivity api={api} projectId={project.id} taskId={task.id} phase={["defining","implementation","reviewing"].includes(currentTask.stage)?currentTask.stage as Phase:undefined}/></aside></div>
    {showRevisions&&<div className="scrim"><section ref={dialog} className="revision-dialog" role="dialog" aria-modal="true" aria-labelledby="revisions-title"><h2 id="revisions-title">Document revisions {selected?.present?"· current":"· deleted"}</h2><div className="revision-grid"><nav>{revisions.map(r=><button key={r.id} aria-current={revision?.id===r.id?"true":undefined} onClick={()=>setRevision(r)}>{new Date(r.captured_at).toLocaleString()} · {r.cause}<small>{r.content_hash.slice(0,10)}</small></button>)}</nav><pre>{revision?new TextDecoder().decode(new Uint8Array(revision.content)):"No revisions"}</pre></div>{error&&<p role="alert">{error}</p>}<div className="actions"><button onClick={()=>setShowRevisions(false)}>Close</button>{!readOnly&&<button className="primary" disabled={!revision} onClick={()=>void restore()}>Restore revision</button>}</div></section></div>}
  </section>;
}
