import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { vi } from "vitest";
import { UpdateControl } from "./UpdateControl";

beforeEach(() => localStorage.clear());
test("throttles automatic checks for 24 hours", async () => { localStorage.setItem("craftel.update.lastCheck", "1000"); const check=vi.fn(); render(<UpdateControl service={{check,relaunch:vi.fn()}} now={()=>2000}/>); await Promise.resolve(); expect(check).not.toHaveBeenCalled(); });
test("checks, downloads only after confirmation, installs, disposes, and restarts", async () => { const relaunch=vi.fn(), dispose=vi.fn().mockResolvedValue(undefined), install=vi.fn(async cb=>cb(10,10)); const service={check:vi.fn().mockResolvedValue({version:"0.1.1",notes:"Fixes",downloadAndInstall:install,dispose}),relaunch}; render(<UpdateControl service={service} now={()=>100_000_000}/>); expect(await screen.findByText(/Version 0.1.1/)).toBeInTheDocument(); expect(install).not.toHaveBeenCalled(); await userEvent.click(screen.getByRole("button",{name:"Download"})); expect(await screen.findByText(/Restart to finish/)).toBeInTheDocument(); expect(dispose).toHaveBeenCalled(); await userEvent.click(screen.getByRole("button",{name:"Restart to update"})); expect(relaunch).toHaveBeenCalled(); });
test("reports no update and permits retry after errors", async () => { const check=vi.fn().mockRejectedValueOnce(new Error("offline")).mockResolvedValue(null); localStorage.setItem("craftel.update.lastCheck",String(Date.now())); render(<UpdateControl service={{check,relaunch:vi.fn()}}/>); await userEvent.click(screen.getByRole("button",{name:"Check for updates"})); expect(await screen.findByRole("alert")).toHaveTextContent("offline"); await userEvent.click(screen.getByRole("button",{name:"Check for updates"})); await waitFor(()=>expect(screen.getByText(/up to date/)).toBeInTheDocument()); });
test("throttles failed automatic checks but still allows a manual retry", async () => { const check=vi.fn().mockRejectedValue(new Error("offline")); const now=100_000_000; const first=render(<UpdateControl service={{check,relaunch:vi.fn()}} now={()=>now}/>); expect(await screen.findByRole("alert")).toHaveTextContent("offline"); first.unmount(); render(<UpdateControl service={{check,relaunch:vi.fn()}} now={()=>now+1000}/>); await Promise.resolve(); expect(check).toHaveBeenCalledTimes(1); await userEvent.click(screen.getByRole("button",{name:"Check for updates"})); expect(check).toHaveBeenCalledTimes(2); });
test("reports restart failures and permits retry", async () => { const relaunch=vi.fn().mockRejectedValueOnce(new Error("busy")).mockResolvedValue(undefined); const update={version:"0.1.1",downloadAndInstall:vi.fn().mockResolvedValue(undefined),dispose:vi.fn().mockResolvedValue(undefined)}; localStorage.setItem("craftel.update.lastCheck",String(Date.now())); render(<UpdateControl service={{check:vi.fn().mockResolvedValue(update),relaunch}}/>); await userEvent.click(screen.getByRole("button",{name:"Check for updates"})); await userEvent.click(await screen.findByRole("button",{name:"Download"})); await userEvent.click(await screen.findByRole("button",{name:"Restart to update"})); expect(await screen.findByRole("alert")).toHaveTextContent("busy"); await userEvent.click(screen.getByRole("button",{name:"Restart to update"})); expect(relaunch).toHaveBeenCalledTimes(2); });
