import { readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import process from "node:process";

const root = new URL("../", import.meta.url), desktop = new URL("../apps/desktop/", import.meta.url), overlay = new URL("src-tauri/tauri.release.conf.json", desktop);
const RELEASE_BASE_VERSION = "0.1.0";
const readJson = url => JSON.parse(readFileSync(url, "utf8"));
const versions = () => ({ package: readJson(new URL("package.json", desktop)).version, tauri: readJson(new URL("src-tauri/tauri.conf.json", desktop)).version, cargo: readFileSync(new URL("src-tauri/Cargo.toml", desktop), "utf8").match(/^version = "([^"]+)"/m)?.[1] });
export function nextPatchVersion(current) { const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(current || ""); if (!match) throw new Error(`Invalid stable version: ${current}`); return `${match[1]}.${match[2]}.${Number(match[3]) + 1}`; }
export function assertPatchUpgrade(current, next) { const expected = nextPatchVersion(current); if (next !== expected) throw new Error(`Patch-only releases require ${expected}; received ${next || "no version"}`); }
export function assertReleaseSequence(previous, current) { assertPatchUpgrade(previous || RELEASE_BASE_VERSION, current); }
export function requestedPatchVersion(current, requested) { const next = requested || nextPatchVersion(current); assertPatchUpgrade(current, next); return next; }
function synchronizedVersion() { const found = versions(), unique = new Set(Object.values(found)); if (unique.size !== 1 || !found.package) throw new Error(`Version mismatch: ${JSON.stringify(found)}`); nextPatchVersion(found.package); return found.package; }
function releaseTags() { return execFileSync("git", ["tag", "--list", "v*", "--sort=-version:refname"], { cwd: root, encoding: "utf8" }).split("\n").filter(tag => /^v\d+\.\d+\.\d+$/.test(tag)); }
function check({ requireClean = true } = {}) { const current = synchronizedVersion(), expectedTag = `v${current}`; const headTags = process.env.GITHUB_REF_TYPE === "tag" ? [process.env.GITHUB_REF_NAME] : execFileSync("git", ["tag", "--points-at", "HEAD"], { cwd: root, encoding: "utf8" }).split("\n").filter(tag => /^v\d+\.\d+\.\d+$/.test(tag)); if (headTags.length > 1) throw new Error(`Release commit has multiple version tags: ${headTags.join(", ")}`); const tag = headTags[0]; if (tag && tag !== expectedTag) throw new Error(`Tag ${tag} must equal ${expectedTag}`); const tags = releaseTags(); if (tags.includes(expectedTag) && tag !== expectedTag) throw new Error(`${expectedTag} already exists on another commit`); const previous = tags.find(value => value !== expectedTag); assertReleaseSequence(previous?.slice(1), current); if (requireClean && execFileSync("git", ["status", "--porcelain"], { cwd: root, encoding: "utf8" }).trim()) throw new Error("Working tree is not clean"); console.log(`Release preflight OK: ${current}${tag ? ` (${tag})` : " (no tag)"}`); }
function configure() { const pubkey = process.env.TAURI_UPDATER_PUBLIC_KEY; if (!pubkey?.trim()) throw new Error("TAURI_UPDATER_PUBLIC_KEY is required"); writeFileSync(overlay, `${JSON.stringify({ bundle: { createUpdaterArtifacts: true }, plugins: { updater: { pubkey, endpoints: ["https://github.com/chanlerdev/craftel/releases/latest/download/latest.json"] } } }, null, 2)}\n`, { mode: 0o600 }); }
function version(requested) { const current = synchronizedVersion(), next = requestedPatchVersion(current, requested); const pkgUrl=new URL("package.json",desktop), confUrl=new URL("src-tauri/tauri.conf.json",desktop), cargoUrl=new URL("src-tauri/Cargo.toml",desktop); const pkg=readJson(pkgUrl),conf=readJson(confUrl); pkg.version=conf.version=next; writeFileSync(pkgUrl,JSON.stringify(pkg,null,2)+"\n"); writeFileSync(confUrl,JSON.stringify(conf,null,2)+"\n"); writeFileSync(cargoUrl,readFileSync(cargoUrl,"utf8").replace(/^version = "[^"]+"/m,`version = "${next}"`)); execFileSync("cargo",["check","--manifest-path",new URL("src-tauri/Cargo.toml",desktop).pathname],{cwd:root,stdio:"inherit"}); console.log(`Advanced desktop patch version from ${current} to ${next}; no commit, tag, or push was performed.`); }
function mac(target) { if (process.platform !== "darwin") throw new Error("release:mac must run on macOS"); if (!target || !["aarch64-apple-darwin","x86_64-apple-darwin"].includes(target)) throw new Error("Usage: pnpm release:mac <aarch64-apple-darwin|x86_64-apple-darwin>"); check(); configure(); try { execFileSync("pnpm",["--filter","@craftel/desktop","tauri","build","--target",target,"--config",overlay.pathname],{cwd:root,stdio:"inherit",env:{...process.env,APPLE_SIGNING_IDENTITY:process.env.APPLE_SIGNING_IDENTITY||"-"}}); } finally { try { unlinkSync(overlay); } catch {} } }
function main() { const [command,arg]=process.argv.slice(2); try { if(command==="check")check(); else if(command==="configure")configure(); else if(command==="next")console.log(nextPatchVersion(synchronizedVersion())); else if(command==="version")version(arg); else if(command==="mac")mac(arg); else throw new Error("Expected check, configure, next, version, or mac"); } catch(error) { console.error(error.message); process.exit(1); } }
if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) main();
