import { readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { execFileSync } from "node:child_process";
import process from "node:process";

const root = new URL("../", import.meta.url), desktop = new URL("../apps/desktop/", import.meta.url), overlay = new URL("src-tauri/tauri.release.conf.json", desktop);
const readJson = url => JSON.parse(readFileSync(url, "utf8"));
const versions = () => ({ package: readJson(new URL("package.json", desktop)).version, tauri: readJson(new URL("src-tauri/tauri.conf.json", desktop)).version, cargo: readFileSync(new URL("src-tauri/Cargo.toml", desktop), "utf8").match(/^version = "([^"]+)"/m)?.[1] });
function check({ requireClean = true } = {}) { const found = versions(), unique = new Set(Object.values(found)); if (unique.size !== 1) throw new Error(`Version mismatch: ${JSON.stringify(found)}`); const tag = process.env.GITHUB_REF_TYPE === "tag" ? process.env.GITHUB_REF_NAME : execFileSync("git", ["tag", "--points-at", "HEAD"], { cwd: root, encoding: "utf8" }).trim(); if (tag && tag !== `v${found.package}`) throw new Error(`Tag ${tag} must equal v${found.package}`); if (requireClean && execFileSync("git", ["status", "--porcelain"], { cwd: root, encoding: "utf8" }).trim()) throw new Error("Working tree is not clean"); console.log(`Release preflight OK: ${found.package}${tag ? ` (${tag})` : " (no tag)"}`); }
function configure() { const pubkey = process.env.TAURI_UPDATER_PUBLIC_KEY; if (!pubkey?.trim()) throw new Error("TAURI_UPDATER_PUBLIC_KEY is required"); writeFileSync(overlay, `${JSON.stringify({ bundle: { createUpdaterArtifacts: true }, plugins: { updater: { pubkey, endpoints: ["https://github.com/chanlerdev/craftel/releases/latest/download/latest.json"] } } }, null, 2)}\n`, { mode: 0o600 }); }
function version(next) { if (!/^\d+\.\d+\.\d+$/.test(next || "")) throw new Error("Usage: pnpm release:version <major.minor.patch>"); const pkgUrl=new URL("package.json",desktop), confUrl=new URL("src-tauri/tauri.conf.json",desktop), cargoUrl=new URL("src-tauri/Cargo.toml",desktop); const pkg=readJson(pkgUrl),conf=readJson(confUrl); pkg.version=conf.version=next; writeFileSync(pkgUrl,JSON.stringify(pkg,null,2)+"\n"); writeFileSync(confUrl,JSON.stringify(conf,null,2)+"\n"); writeFileSync(cargoUrl,readFileSync(cargoUrl,"utf8").replace(/^version = "[^"]+"/m,`version = "${next}"`)); execFileSync("cargo",["check","--manifest-path",new URL("src-tauri/Cargo.toml",desktop).pathname],{cwd:root,stdio:"inherit"}); console.log(`Set desktop version to ${next}; no commit, tag, or push was performed.`); }
function mac(target) { if (process.platform !== "darwin") throw new Error("release:mac must run on macOS"); if (!target || !["aarch64-apple-darwin","x86_64-apple-darwin"].includes(target)) throw new Error("Usage: pnpm release:mac <aarch64-apple-darwin|x86_64-apple-darwin>"); check(); configure(); try { execFileSync("pnpm",["--filter","@craftel/desktop","tauri","build","--target",target,"--config",overlay.pathname],{cwd:root,stdio:"inherit",env:{...process.env,APPLE_SIGNING_IDENTITY:process.env.APPLE_SIGNING_IDENTITY||"-"}}); } finally { try { unlinkSync(overlay); } catch {} } }
const [command,arg]=process.argv.slice(2); try { if(command==="check")check(); else if(command==="configure")configure(); else if(command==="version")version(arg); else if(command==="mac")mac(arg); else throw new Error("Expected check, configure, version, or mac"); } catch(error) { console.error(error.message); process.exit(1); }
